apiVersion: kubernetes.dask.org/v1
kind: DaskCluster
metadata:
  name: evaluator-lw
spec:
  idleTimeout: 0
  scheduler:
    service:
      ports:
      - name: tcp-comm
        port: 8786
        protocol: TCP
        targetPort: tcp-comm
      - name: http-dashboard
        port: 8787
        protocol: TCP
        targetPort: http-dashboard
      selector:
        dask.org/cluster-name: evaluator-lw
        dask.org/component: scheduler
      type: ClusterIP
    spec:
      containers:
      - args:
        - dask-scheduler
        - --host
        - 0.0.0.0
        env:
        - name: OE_LICENSE
          value: /secrets/oe_license.txt
        - name: DASK_DISTRIBUTED__WORKER__DAEMON
          value: 'False'
        - name: DASK__TEMPORARY_DIRECTORY
          value: /evaluator-storage
        - name: STORAGE_DIRECTORY
          value: /evaluator-storage
        image: ghcr.io/lilyminium/openff-images:evaluator-0.4.10-kubernetes-backend-dask-v2
        livenessProbe:
          httpGet:
            path: /health
            port: http-dashboard
          initialDelaySeconds: 15
          periodSeconds: 20
        name: scheduler
        ports:
        - containerPort: 8786
          name: tcp-comm
          protocol: TCP
        - containerPort: 8787
          name: http-dashboard
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /health
            port: http-dashboard
          initialDelaySeconds: 0
          periodSeconds: 1
          timeoutSeconds: 3600
        resources:
          limits:
            cpu: '1'
            ephemeral-storage: 20Gi
            memory: 8Gi
          requests:
            cpu: '1'
            ephemeral-storage: 20Gi
            memory: 8Gi
        volumeMounts:
        - mountPath: /evaluator-storage
          name: evaluator-storage-lw
          readOnly: false
        - mountPath: /secrets/oe_license.txt
          name: openeye-license
          readOnly: true
          subPath: oe_license.txt
      volumes:
      - name: evaluator-storage-lw
        persistentVolumeClaim:
          claimName: evaluator-storage-lw
      - name: openeye-license
        secret:
          secretName: oe-license-feb-2024
  worker:
    replicas: 0
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: nvidia.com/cuda.runtime.major
                operator: In
                values:
                - '12'
      containers:
      - args:
        - dask-worker
        - --name
        - $(DASK_WORKER_NAME)
        - --dashboard
        - --dashboard-address
        - '8788'
        env:
        - name: OE_LICENSE
          value: /secrets/oe_license.txt
        - name: DASK_DISTRIBUTED__WORKER__DAEMON
          value: 'False'
        - name: DASK__TEMPORARY_DIRECTORY
          value: /evaluator-storage
        - name: STORAGE_DIRECTORY
          value: /evaluator-storage
        image: ghcr.io/lilyminium/openff-images:evaluator-0.4.10-kubernetes-backend-dask-v2
        imagePullPolicy: Always
        name: worker
        ports:
        - containerPort: 8788
          name: http-dashboard
          protocol: TCP
        resources:
          limits:
            cpu: '1'
            ephemeral-storage: 20Gi
            memory: 8Gi
            nvidia.com/gpu: '1'
          requests:
            cpu: '1'
            ephemeral-storage: 20Gi
            memory: 8Gi
            nvidia.com/gpu: '1'
        volumeMounts:
        - mountPath: /evaluator-storage
          name: evaluator-storage-lw
          readOnly: false
        - mountPath: /secrets/oe_license.txt
          name: openeye-license
          readOnly: true
          subPath: oe_license.txt
      volumes:
      - name: evaluator-storage-lw
        persistentVolumeClaim:
          claimName: evaluator-storage-lw
      - name: openeye-license
        secret:
          secretName: oe-license-feb-2024
