apiVersion: v1
kind: Pod
metadata:
  name: watch-evaluator-lw-pod
  labels:
    k8s-app: test-http2
spec:
  containers:
  - name: mypod
    image: "ghcr.io/lilyminium/openff-images:evaluator-0.4.10-kubernetes-backend-dask-v1"
    env:
    - name: OE_LICENSE
      value: /secrets/oe_license.txt
    command:
      - "/bin/bash"
      - "-c"
      - "ls /evaluator-storage/* && du -hsc /evaluator-storage/* && sleep 3600"

      # - "python"
      # - "-c"
      # - "from openff.toolkit.utils import OPENEYE_AVAILABLE; print(OPENEYE_AVAILABLE)"
      
    volumeMounts:
    - name: evaluator-storage-lw
      mountPath: /evaluator-storage
    - name: openeye-license
      mountPath: /secrets/oe_license.txt
      subPath: oe_license.txt
  volumes:
  - name: evaluator-storage-lw
    persistentVolumeClaim:
      claimName: evaluator-storage-lw

  - name: openeye-license
    secret:
      secretName: oe-license-feb-2024

