apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: evaluator-storage-lw
spec:
  storageClassName: rook-cephfs-east
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
    